name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: AIzaSyBMzO14ALimQFpSGGkV7Ven6fRtABBxvc0
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: money-tracker-22d76.firebaseapp.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: money-tracker-22d76
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: money-tracker-22d76.firebasestorage.app
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 857522441209
          NEXT_PUBLIC_FIREBASE_APP_ID: 1:857522441209:web:1f1a99c662bc5464960b28
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
